config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root to: "pages#home"
  get "footprint", to: "pages#footprint"

  resources :trips, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[create]
    member do
      get "trains"
      get "book"
    end
  end

  resources :bookmarks, only: %i[index update destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :trip
  belongs_to :user

  enum :status, { not_done: 0, to_do: 1, done: 2 }

  after_update_commit :broadcast_bookmark

  private

  def broadcast_bookmark
    broadcast_append_to "done_bookmarks_#{self.user.id}",
                        partial: "bookmarks/done_bookmark",
                        locals: { bookmark: self }
    broadcast_remove_to "to_do_bookmarks_#{self.user.id}"
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: %i[update]

  def index
    # @bookmarks = Bookmark.all
    @to_do_bookmarks = Bookmark.where(user: current_user).where(status: :to_do)
    @done_bookmarks = Bookmark.where(user: current_user).where(status: :done)
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user = current_user
    @bookmark.status = :to_do
    if @bookmark.save
      redirect_to trip_path(@bookmark.trip)
    else
      flash[:alert] = "Unable to bookmark the trip"
      redirect_to trip_path(@bookmark.trip)
    end
  end

  def update
    @bookmark.status = params[:status]
    if @bookmark.save
      redirect_to bookmarks_path
    else
      flash[:alert] = "Unable to update the trip"
      redirect_to bookmarks_path
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

   # if @bookmark.destroy
     # redirect_to trip_path(@bookmark.trip), notice: "Bookmark removed."
   # else
      #render "trips/show", alert: "Unable to remove bookmark."

    if @bookmark.user == current_user
      @bookmark.destroy
      flash[:notice] = "Trip removed"
      if params[:bookmark_id]
        redirect_to bookmarks_path
      else
        redirect_to trip_path(@bookmark.trip)
      end
    else
      flash[:alert] = "Unable to remove the trip"
      redirect_to bookmarks_path
    end
  end

  private

  def bookmark_params
    # params.require(:bookmark).permit(:status)
    params.permit(:trip_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/views/bookmarks/_done_bookmark.html.erb
<div class="row" id="bookmark-id<%= bookmark.id %>">
  <div class="card-bookmark">
    <% if bookmark.trip.photo.present? %>
      <%= cl_image_tag bookmark.trip.photo.key, class: "card-index-background" %>
    <% else %>
      <img class="card-index-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D">
    <% end %>
    <%# <img class="card-bookmark-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D"> %>
    <div class="card-bookmark-content">
      <%= link_to bookmark_path(bookmark, bookmark_id: bookmark.id), class: 'btn btn-light position-absolute top-0 end-0 m-3', data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
      <h3><%= link_to bookmark.trip.title, trip_path(bookmark.trip), class: 'text-decoration-none' %></h3>
      <p><%= bookmark.trip.description %></p>
      <div class="justify-content-between">
        <%= link_to 'Add a Review', new_bookmark_review_path(bookmark, status: :done), class: 'btn-bookmark' %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/_to_do_bookmark.html.erb
<div class="row" id="bookmark-id<%= bookmark.id %>">
  <div class="card-bookmark">
    <% if bookmark.trip.photo.present? %>
      <%= cl_image_tag bookmark.trip.photo.key, class: "card-index-background" %>
    <% else %>
      <img class="card-index-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D">
    <% end %>
    <%# <img class="card-bookmark-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D"> %>
    <div class="card-bookmark-content">
      <%= link_to bookmark_path(bookmark, bookmark_id: bookmark.id), class: 'btn btn-light position-absolute top-0 end-0 m-3', data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
      <h3><%= link_to bookmark.trip.title, trip_path(bookmark.trip), class: 'text-decoration-none' %></h3>
      <p><%= bookmark.trip.description %></p>
      <div class="justify-content-between">
        <%= link_to 'Book', trains_trip_path(bookmark.trip), class: 'btn-bookmark' %>
        <%= link_to 'Mark as Done', bookmark_path(bookmark, status: :done), class: 'btn-bookmark', data: { turbo_method: :patch } %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/index.html.erb
<div class="margin-navbar"></div>

<div class="mt-2 mx-5 text-center">
  <h1>My trips</h1>
</div>

<div class="container-show-trip">
  <div class="mt-5 text-center">
    <h2>Trips to-do</h2>
  </div>
  <div class="container-card">
    <% if @to_do_bookmarks.any? %>
      <div class="row" id="to_do_bookmarks">
        <div class="cards-bookmark-grid">
          <% @to_do_bookmarks.each do |bookmark| %>
            <%= render partial: "to_do_bookmark", locals: { bookmark: bookmark } %>
          <% end %>
        </div>
      </div>
    <% else %>
      <p>You have no bookmarks yet.</p>
    <% end %>
  </div>

  <div class="mt-2 text-center">
    <h2>Trips done</h2>
  </div>
  <div class="container-card">
    <% if @done_bookmarks.any? %>
      <div class="row" id="done_bookmarks">
        <div class="cards-bookmark-grid">
          <% @done_bookmarks.each do |bookmark| %>
            <%= render partial: "done_bookmark", locals: { bookmark: bookmark } %>
          <% end %>
        </div>
        </div>
    <% else %>
      <p>No bookmarks marked as done yet.</p>
    <% end %>
  </div>
</div>

app/views/bookmarks/update_done_bookmarks.turbo_stream.erb
<%# <%= turbo_stream.replace 'done_bookmarks' do %> 
  <%= render partial: 'bookmarks/done_bookmark', locals: { bookmark: bookmark } %>
<%# <% end %>