config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root to: "pages#home"
  get "footprint", to: "pages#footprint"

  resources :trips, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[create]
    member do
      get "trains"
      get "book"
    end
  end

  resources :bookmarks, only: %i[index update destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :categories
  has_many :footprints, dependent: :destroy

  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true

  require "open-uri"
  require "json"
  require "nokogiri"

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [ :title, :description],
  using: {
    tsearch: { prefix: true }
  }
  #validates :footprint, presence: true
  #before_save :set_total_duration, :set_footprint

  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  def set_total_distance_and_duration
    self.total_duration = 0
    self.total_distance = 0
    self.steps.each_with_index do |step, index|
      self.total_duration += step.duration
      if index > 0
        previous_step = self.steps[index-1]
        step.distance = Geocoder::Calculations.distance_between([step.latitude, step.longitude], [previous_step.latitude, previous_step.longitude])
      elsif index == 0
        step.distance = 0
      end
      step.save
      self.total_distance += step.distance
    end
    self.save
    puts "trip distance and duration are set"
  end

  def set_footprint
    url = "https://impactco2.fr/api/v1/transport?km=#{self.total_distance}&displayAll=0&transports=2%2C%201%2C%204&ignoreRadiativeForcing=0&occupencyRate=1&includeConstruction=1&language=en"
    html_file = URI.open(url).read
    data = JSON.parse(html_file)
    data["data"].each_with_index do |element, index|
      if index == 0
        transport = Transport.find_or_create_by(name: "Plane")
      elsif index == 1
        transport = Transport.find_or_create_by(name: "Train")
      elsif index == 2
        transport = Transport.find_or_create_by(name: "Car")
      end
      Footprint.create(transport: transport, trip: self, value: element["value"].to_i)
      puts "trip footprint is set"
    end
  end

  def trainline
    # url = "https://www.trainline.fr/search/#{self.steps.first.title.split[0]}/#{self.steps.last.title.split[0]}"
    # html_file = URI.open(url).read
    # html_doc = Nokogiri::HTML.parse(html_file)
    # @data = html_doc
    @url = "https://www.trainline.fr/search/#{self.steps.first.title.split[0]}/#{self.steps.last.title.split[0]}"
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @trips = Trip.all
    if params[:search] && params[:search][:query].present?
      @trips = Trip.search_by_title_and_description(params[:search][:query])
    elsif params[:category].present?
      @trips = Trip.where('category LIKE ?', "%#{params[:category]}%")
    elsif params[:trip] && params[:trip][:total_distance].present?
      @trips = Trip.where('total_distance <= ?', "#{params[:trip][:total_distance]}")
    elsif params[:trip] && params[:trip][:total_duration].present?
      @trips = Trip.where('total_duration <= ?', "#{params[:trip][:total_duration]}")
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @reviews = @trip.reviews
    @user_trip_bookmark = Bookmark.find_by(user: current_user, trip: @trip)
    @markers = @trip.steps.order(:order).map do |step|
      {
        lat: step.latitude,
        lng: step.longitude,
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def trains
    @trip = Trip.find(params[:id])
    @reviews = @trip.reviews
    @user_trip_bookmark = Bookmark.find_by(user: current_user, trip: @trip)
  end

  def book
    trip = Trip.find(params[:id])
    step_depart = Step.find(params[:step]).title.split[0]
    step_arrivee = trip.steps[params[:index].to_i+1].title.split[0]
    url = "https://www.trainline.fr/search/#{step_depart}/#{step_arrivee}"
    button = ClicTrainsApi.new(url)
    button.call
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    @trip.category = params[:trip][:category].join(" ").strip
    if @trip.save
      const = 0
      @trip.steps.each do |step|
        step.order = const
        const += 1
        step.save
      end
      @trip.set_total_distance_and_duration
      @trip.set_footprint
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :description, :category, :total_distance, :total_duration, :photo, steps_attributes: %i[id destroy duration content title photo])
  end
end

app/views/trips/_form.html.erb
<%= simple_form_for @trip,
            data: {
              controller: 'nested-form coordinates',
              nested_form_wrapper_selector_value: '.nested-form-wrapper',
              action: "submit->coordinates#setcoordinates"
                  } do |f| %>
  <%= f.input :title, label: 'Trip title' %>
  <%= f.input :description, label: 'Trip description' %>
  <%= f.input :category,
              collection: ["Capitals Cities", "Beach Escapes", "Mountain Getaways", "Rural Retreats"],
              as: :check_boxes,
              input_html: { class: "tag-selector" },
              item_wrapper_class: 'tag-item' %>
  <%= f.input :photo, label: 'Add a trip picture', as: :file %>

  <div class="m-3 myinnerborder">
    <div class="m-3">
        <!-- Template for new records -->
        <template data-nested-form-target="template">
          <%= f.simple_fields_for :steps, Step.new, child_index: 'NEW_RECORD' do |step_fields| %>
            <%= render "shared/step_form", f: step_fields %>
          <% end %>
        </template>

        <!-- Existing records -->
        <%= f.simple_fields_for :steps do |step_fields| %>
          <%= render "shared/step_form", f: step_fields %>
        <% end %>

        <div data-nested-form-target="target"></div>
        <button class="btn-general-pink" data-action="nested-form#add">Add step</button>
    </div>
  </div>

  <div class="text-center" >
    <%= f.button :submit, "Submit trip", class: "btn-submit-pink" %>
  </div>
<% end %>

app/views/trips/_marker.html.erb
<%= image_tag "newmarker.png", height: 40, width: 40, alt: "tchou" %>

app/views/trips/book.html.erb
Redirection

app/views/trips/index.html.erb
<div class="margin-navbar"></div>


<!--<h2 class="text-center">Find your adventure</h2>-->

<% if params[:search] && params[:search][:query].present? %>
  <h3 class="text-center">Results for: "<%= params[:search][:query] %>"</h3>
<% end %>

<div class="container-search">
  <div>
    <%= simple_form_for :search, url: trips_path, method: :get do |f| %>
      <div class="search-form-control form-group mb-3 mt-4">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" />
        <button name="button" type="submit" class="btn btn-flat">
        <p class="search-placeholder"><i class="fas fa-search"></i></p>
        </button>
      </div>
    <% end %>
  </div>

  <div class="dropdown">
    <button class="btn-middle-pink dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Categories
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Capital Cities", trips_path(category: "Capital Cities"), class: "dropdown-item" %></li>
      <li><%= link_to "Beach Escapes", trips_path(category: "Beach Escapes"), class: "dropdown-item" %></li>
      <li><%= link_to "Mountain Gateaways", trips_path(category: "Mountain Gateaways"), class: "dropdown-item" %></li>
      <li><%= link_to "Rural Retreats", trips_path(category: "Rural Retreats"), class: "dropdown-item" %></li>
    </ul>
  </div>
  <div class="dropdown">
    <button class="btn-middle-pink dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Days
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= simple_form_for Trip.new, url: trips_path, method: :get, html:{class: "index-slider"} do |f| %>
          <%= f.input :total_duration, as: :range, input_html: { min: 0, max: 30, data: { controller: "filter", action: "input->filter#updateValue" } }, label: false %>
          <%= f.button :submit, "See results", class: "btn-general-pink btn-submit" %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="dropdown">
    <button class="btn-general-pink dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Distance
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= simple_form_for Trip.new, url: trips_path, method: :get, html:{class: "index-slider"} do |f| %>
          <%= f.input :total_distance, as: :range, input_html: { min: 0, max: 1500, data: { controller: "filter", action: "input->filter#updateValue" } }, label: false %>
          <%= f.button :submit, "See results", class: "btn-general-pink btn-submit" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<div class="container-card">
  <div class="cards-index-grid">
    <% @trips.each do |trip| %>
    <%# ---------SETUP--------- %>
    <% plane = trip.footprints.first.value.to_i %>
    <% train = trip.footprints.second.value.to_i %>
    <% car = trip.footprints.last.value.to_i %>
    <%# ---------/SETUP--------- %>
      <%= link_to trip_path(trip), class: "card-index" do %>
        <% if trip.photo.present? %>
          <%= cl_image_tag trip.photo.key, class: "card-index-background" %>
        <% else %>
          <img class="card-index-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D">
        <% end %>
        <div class="card-index-content">
          <h3><%= trip.title %></h3>
          <p class="text-white"><%= trip.steps.count %> steps
          <p class="text-white"><%= "#{trip.total_duration} days" %>
          <p class="text-white"><%= "#{trip.total_distance} km" %></p>
        </div>
         <div class="badge-pill-index">
          <%= plane - train %> kg CO₂ avoided
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="margin-navbar"></div>
<h1 class="text-center">Trip creation</h1>

<div class="m-5">
  <div class="m-5">
    <div class="m-5">
      <div class="m-5 myborder">
        <div class="m-5">
          <%= render "trips/form", trip: @trip %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="margin-navbar"></div>

<%# ---------SETUP--------- %>
<% plane = @trip.footprints.first.value.to_i %>
<% train = @trip.footprints.second.value.to_i %>
<% car = @trip.footprints.last.value.to_i %>
<%# ---------/SETUP--------- %>

<div class="container-show-trip">
  <%# ---------Titres, distance, temps, Co2--------- %>
  <div class="">
    <div class="d-flex gap-3 align-items-center ">
      <h1 class=""><%= @trip.title %></h1>
      <% if @user_trip_bookmark.present? && @user_trip_bookmark.to_do? %>
        <%= link_to bookmark_path(@user_trip_bookmark), data: { turbo_method: :delete }, class: "btn btn-lg" do %>
          <i class="bi bi-bookmark-check-fill"></i>
        <% end %>
      <% else %>
        <%= link_to trip_bookmarks_path(trip_id: @trip.id, authenticity_token: form_authenticity_token), data: { turbo_method: :create }, class: "btn btn-lg" do %>
          <i class="bi bi-bookmark-plus"></i>
        <% end %>
      <% end %>
    </div>
    <h5><%= "#{@trip.steps.count} steps - #{@trip.total_duration} days - #{@trip.total_distance} km" %></h5>
    <p class=""><%= @trip.description %></p>
  </div>
  <!--  <p>This trip saves <%#= plane - train %> kg of CO₂ compared to air travel.</p>-->

  <%# ---------PDP Lucas--------- %>
  <div class="row align-items-stretch">
    <div class="col-5">
      <div
        style="width: 100%; height: 500px; position"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        class="rounded"
      >
        <div class="badge-pill">
          <%= plane - train %> kg CO₂ avoided
        </div>
      </div>
    </div>

    <div class="col-7 carousel-step">
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner mt-3">
          <% @trip.steps.sort_by(&:order).each_with_index do |step, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <p class="mt-1 text-secondary text-center"><b>Step <%= index + 1 %></b></p>
              <h5 class="text-center"><%= "#{step.title.split[0]} #{step.title.split[-1]}" %></h5>
              <% if step.photo.present? %>
                <div class="d-flex justify-content-center mt-3 mb-3">
                  <%= cl_image_tag step.photo.key, class: "img-show" %>
                  <%# <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                </div>
              <% else %>
                <div class="d-flex justify-content-center mt-3 mb-3">
                  <img
                    src="https://images.pexels.com/photos/1059078/pexels-photo-1059078.jpeg"
                    src=""
                    class="img-show"
                  >
                </div>
              <% end %>
              <div class="carousel-desc">
                <h5>Description</h5>
                <p class="text-wrap"><%= step.content %></p>
                <p><%= "⏱️ #{step.duration} days 📍 #{step.distance} km" %></p>
              </div>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#243264" class="bi bi-chevron-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
          </svg>
          <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#243264" class="bi bi-chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
          </svg>

          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>
  <% if @reviews.present? %>
    <div class="mt-5 mb-4">
      <h2>Reviews ( <%= @reviews.count %> )</h2>
    </div>
  <% end %>

  <div class="cards-reviews-grid">
    <% @reviews.each do |review| %>
      <div class="card-review">
        <div class="card-review-top-content">
          <div class="card-review-user-content">
            <%= image_tag review.user.picture, class: "card-review-user-picture" %>
          </div>
          <ul class="star-rating-display">
            <% rating = review.rating || 0 %> <!-- Définit la note à 0 si elle est nil -->
            <% 5.times do |i| %>
              <% if i < rating %>
                <li><i class="fa-solid fa-star"></i></li>
              <% else %>
                <li><i class="fa-regular fa-star"></i></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <article>
          <p><%= review.content %></p>
        </article>
      </div>
    <% end %>
  </div>
</div>

app/views/trips/trains.html.erb
<div class="margin-navbar"></div>

<h2 class="text-center">Book your trains</h2>

<div class="container-card">
  <div class="card-train m-3">
    <div class="card-train-content">
      <% @trip.steps.order(:order).each_with_index do |step, index| %>
        <% next if @trip.steps.length - 1 == index %>
        <% step_depart = step.title.split[0] %>
        <% step_arrivee = @trip.steps.order(:order)[index+1].title.split[0] %>
        <% num = index + 1 %>
        <% url = "https://www.trainline.fr/search/#{step_depart}/#{step_arrivee}" %>

        <div class="d-flex flex-inline my-4">
          <p class="blue-underline"><%= "Step #{num} : #{step_depart[0...-1]} to #{step_arrivee[0...-1]}" %></p>
          <%# raise %>
          <div class="mx-2">
            <a href=<%="#{url}" %> class="btn-small-blue" target="_blank" > See trains </a>
          </div>
        </div>
      <% end%>
    </div>
  </div>
</div>





<!--
<div class="margin-navbar"></div>
<div class="container">
  <h2 class="text-center">Book your trains</h2>
  <%# @trip.steps.each_with_index do |step, index| %>-->
    <%# next if @trip.steps.length - 1 == index %>
    <%# step_depart = step.title.split[0] %>
    <%# step_arrivee = @trip.steps[index+1].title.split[0] %>
    <%# num = index + 1 %>
<!--    <div class="d-flex flex-inline my-4">
      <p class="blue-underline"><%#= "Step #{num} : #{step_depart} to #{step_arrivee}" %></p>
      <div class="mx-2">
        <%#= link_to "See Trains", book_trip_path(trip: @trip, step: step, index: index), input_html: { class: "btn-small-blue" } %>-->
<!--      </div>
    </div>
  <%# end%>-->
<!--</div>
-->