config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root to: "pages#home"
  get "footprint", to: "pages#footprint"

  resources :trips, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[create]
    member do
      get "trains"
      get "book"
    end
  end

  resources :bookmarks, only: %i[index update destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/views/shared/_flashes.html.erb
<% if flash[:success] %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong>Yay !</strong> 🎉 <%= flash[:success] %> </span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 <%= flash[:notice] %> </span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><strong>Oops !</strong> 😱 <%= flash[:alert] %> </span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer p-3 justify-content-center">
  <div class="row">
    <div class="col-md-8">
      <h5 class="text-uppercase">Looking for other stopovers ?<br> Join our journey !</h5>
      <div class="form-outline form-white d-flex">
        <input type="email" id="email-footer" placeholder="name@mail.com" class="form-control py-2 my-3" />
        <button type="submit" class="btn-subscribe py-2 my-3">Subscribe</button>
      </div>
      <div class="mt-5">
        <button type="button" class="btn-social btn-sm btn-floating mx-2 ">
          <i class="fab fa-facebook" ></i>
        </button>
        <button type="button" class="btn-social btn-sm btn-floating mx-2">
          <i class="fab fa-youtube"></i>
        </button>
        <button type="button" class="btn-social btn-sm btn-floating mx-2">
          <i class="fab fa-instagram"></i>
        </button>
        <button type="button" class="btn-social btn-sm btn-floating mx-2">
          <i class="fab fa-twitter"></i>
        </button>
      </div>
    </div>
    <div class="col-6 col-md-4 text-end">
      <h5 class="text-uppercase mb-4">About Us</h5>
      <ul class="list-unstyled">
        <li><a href="https://www.linkedin.com/in/vincent-gannier/" class="text-decoration-none">Vincent Gannier</a></li>
        <li><a href="#!" class="text-decoration-none">Enzo Bertevas</a></li>
        <li><a href="#!" class="text-decoration-none">Lucas Maillet</a></li>
        <li><a href="#!" class="text-decoration-none">Alexandre Guilmet</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <div class="col-11 text-center" >
          <h5 class="modal-title">My trip</h5>
        </div>
        <div class="col-1" >
          <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
        </div>
      </div>

      <div class="modal-body">
        <%= render "trips/form" %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!--<nav class="navbar d-flex justify-content-between align-items-center" id="navbar">

  <div class="d-flex flex row logo">
     <h1 id="navbar_title" ><%#= link_to "Escale", root_path, class: "text-decoration-none " %></h1>
  </div>
  <div>
    <ul class="nav-list">
        <li class="nav-link"><%#= link_to "Trips", trips_path %></li>
        <li class="nav-link"><%#= link_to "My trips", bookmarks_path %></li>
        <li class="nav-link"><%#= link_to "Footprint", footprint_path %></li>
    </ul>
  </div>
  <div class="d-flex align-items-center justify-content-between my-2">
    <div class="navbar-button me-3">
      <%#= link_to "Create a trip", new_trip_path, class: "text-decoration-none " %>-->
<!--    </div>-->
    <%# if current_user %>
      <%#= image_tag current_user.picture, class: "avatar", alt: "Profile picture" %>
    <%# else %>
      <%#= link_to "Login", new_user_session_path, class: "white text-decoration-none" %>
    <%# end %>
<!--  </div>
</nav>
-->

<nav data-controller="hide-navbar-scroll" data-hide-navbar-scroll-target="navbar" class="navbar d-flex justify-content-between align-items-center" id="navbar">
  <div class="d-flex flex row logo">
    <h1 id="navbar_title"><%= link_to "Escale", root_path, class: "text-decoration-none " %></h1>
  </div>
  <div>
    <ul class="nav-list">
      <li class="nav-link"><%= link_to "Trips", trips_path %></li>
      <li class="nav-link"><%= link_to "My trips", bookmarks_path %></li>
      <li class="nav-link"><%= link_to "Footprint", footprint_path %></li>
    </ul>
  </div>
  <div class="d-flex align-items-center justify-content-between my-2">
    <div class="navbar-button me-3">
      <%= link_to "Create a trip", new_trip_path, class: "text-decoration-none " %>
    </div>
    <% if current_user %>
      <%= image_tag current_user.picture, class: "avatar", alt: "Profile picture" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "white text-decoration-none" %>
    <% end %>
  </div>
</nav>

app/views/shared/_step_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

  <%= f.input :title, label: 'Step location',
    input_html: { data: { coordinates_target: "input", address_autocomplete_target: "address" }, class: "d-none" },
    wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value:
    ENV["MAPBOX_API_KEY"] } }, as: :string %>

  <%= f.input :content, label: 'Describe this step', as: :text %>
  <%= f.input :duration, label: 'Step duration in days', as: :integer %>
  <%= f.input :photo, label: 'Add a step picture', as: :file %>

  <button class="btn-general-blue" data-action="nested-form#remove">Remove step</button>
  <%= f.input :_destroy, as: :hidden %>
</div>