config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root to: "pages#home"
  get "footprint", to: "pages#footprint"

  resources :trips, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[create]
    member do
      get "trains"
      get "book"
    end
  end

  resources :bookmarks, only: %i[index update destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/views/pages/footprint.html.erb
<div class="margin-navbar"></div>

<div class="">
  <script name="impact-co2" src="https://impactco2.fr/iframe.js" data-type="transport" data-search="?theme=default&language=en&km=1000&defaultMode=list&comparison=avion,tgv&modes=avion,tgv,voiturethermique,intercites"></script>
</div>

app/views/pages/home.html.erb
<div class="main-banner">
    <h1>ESCALE</h1>
    <h3>Find your next train adventure</h3>

  <%= simple_form_for :search, url: trips_path, method: :get do |f| %>
    <div class="search-form-control form-group mb-3 mt-5">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
      <p class="search-placeholder"><i class="fas fa-search"></i></p>
      </button>
    </div>
  <% end %>
</div>

<div class="container-show-trip">
  <div class="mt-5 mb-4 mx-5">
    <h2>Recommended categories</h2>
  </div>

  <div class="container-card">
    <div class="cards-category-grid">
      <% @categories.each do |k, v| %>
        <%= link_to trips_path(category: k), class: "card-category" do %>
          <img class="card-category-background" src=<%= v %>>
          <div class="card-category-content">
            <p>Category</p>
            <h3><%= k %></h3>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mt-2 mb-4 mx-5">
    <h2>Recently created</h2>
  </div>

  <div class="container-card">
    <div class="cards-index-grid">
      <% @trips.last(3).reverse.each do |trip| %>
    <%# ---------SETUP--------- %>
    <% plane = trip.footprints.first.value.to_i %>
    <% train = trip.footprints.second.value.to_i %>
    <% car = trip.footprints.last.value.to_i %>
    <%# ---------/SETUP--------- %>
      <%= link_to trip_path(trip), class: "card-index" do %>
        <% if trip.photo.present? %>
          <%= cl_image_tag trip.photo.key, class: "card-index-background" %>
        <% else %>
          <img class="card-index-background" src="https://plus.unsplash.com/premium_photo-1674716518188-e5763982eb59?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhaW58ZW58MHx8MHx8fDA%3D">
        <% end %>
        <div class="card-index-content">
          <h3><%= trip.title %></h3>
          <p><i><%= "#{trip.total_duration} days, #{trip.total_distance} km" %></i></p>
          <p><%= trip.steps.count %> steps</p>
        </div>
          <div class="badge-pill-home">
            <%= plane - train %> kg CO₂ avoided
          </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>